require("lihuax.utils.changewd")
require("lihuax.utils.artical")
require("lihuax.utils.makeanki")
require("lihuax.utils.runner")
require("lihuax.utils.encryption")
require("lihuax.utils.mail")
require("lihuax.utils.greek")

local diary = require("lihuax.utils.diary")
vim.api.nvim_create_user_command("DiaryToday", diary.touch_today_diary, {})
vim.api.nvim_set_keymap("n", "<leader>dd", ":DiaryToday<CR>", { noremap = true, silent = true })
vim.api.nvim_create_user_command("DiaryWeekly", diary.touch_weekly_journal, {})
vim.api.nvim_set_keymap("n", "<leader>dw", ":DiaryWeekly<CR>", { noremap = true, silent = true })
vim.api.nvim_create_user_command("DiaryDevWeekly", diary.touch_dev_weekly_journal, {})
vim.api.nvim_set_keymap("n", "<leader>de", ":DiaryDevWeekly<CR>", { noremap = true, silent = true })
